[package]
name = "amazeing_dungeon"
version = "0.1.0"
edition = "2021"
authors = ["Harin Wu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"